name: nodes
description: Being a plugin to facilitate nationstate gameplay within a sandbox environment.
author: jdw-mis
version: 0.0.1
main: com.mis.nodes.Nodes
load: POSTWORLD
database: false
commands:
  node:
    description: Command Switchboard
    aliases: [ n, no, nodes ]
    usage: |
        /<command> create <name> - creates faction.
        /<command> join <faction> - joins faction.
        /<command> invite <player> - invites player to faction.
        /<command> kick <player> - kicks player from faction.
        /<command> promote <player> - promotes player.
        /<command> demote <player> - demotes player.
        /<command> home - teleports to faction home.
        /<command> sethome - sets faction home.
        /<command> map <zoom> [size:1|2|3|4|5] [mode:node|faction] - draws map.
        /<command> name <name> - renames faction.
        /<command> desc <desc> - changes faction description.
        /<command> open - opens faction to any joiner.
        /<command> closes - closes faction to only invited.
        /<command> ally <faction> - sets pending relate to ally with another faction.
        /<command> neutral <faction> - sets pending relate to neutral with another faction.
        /<command> enemy <faction> - enemies another faction.
        /<command> relate <accept|ally|neutral|enemy|delete> <faction> - sets relation with another faction.
        /<command> leave - leaves faction.
        /<command> delete [yes] - deletes faction.
    permission: <plugin name>.no
    permission-message: You don't have <permission>
permissions:
  <plugin name>.no: {description: Command Switchboard, default: true}
  <plugin name>.op: {description: Operator Flag, default: false}